// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiS1BX3uUVu1NcebiH4693ADzOz47pSmw',
    appId: '1:1006479787055:web:7bcf55a77c4253a480b2da',
    messagingSenderId: '1006479787055',
    projectId: 'adwise-4812',
    authDomain: 'adwise-4812.firebaseapp.com',
    storageBucket: 'adwise-4812.appspot.com',
    measurementId: 'G-2NNNYHMW2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Q2PKFZWBCo3c783JQZkup7ee1FvNgWA',
    appId: '1:1006479787055:android:04aee1745978dbc580b2da',
    messagingSenderId: '1006479787055',
    projectId: 'adwise-4812',
    storageBucket: 'adwise-4812.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz83GKq1Bc7P1Y1NeRL6mfpZHaqBliszM',
    appId: '1:1006479787055:ios:f8d4e410571558b480b2da',
    messagingSenderId: '1006479787055',
    projectId: 'adwise-4812',
    storageBucket: 'adwise-4812.appspot.com',
    iosBundleId: 'com.example.kalki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz83GKq1Bc7P1Y1NeRL6mfpZHaqBliszM',
    appId: '1:1006479787055:ios:f8d4e410571558b480b2da',
    messagingSenderId: '1006479787055',
    projectId: 'adwise-4812',
    storageBucket: 'adwise-4812.appspot.com',
    iosBundleId: 'com.example.kalki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiS1BX3uUVu1NcebiH4693ADzOz47pSmw',
    appId: '1:1006479787055:web:3ee1678467b16adc80b2da',
    messagingSenderId: '1006479787055',
    projectId: 'adwise-4812',
    authDomain: 'adwise-4812.firebaseapp.com',
    storageBucket: 'adwise-4812.appspot.com',
    measurementId: 'G-3J8FM64SHW',
  );
}
